[package]
name = "cli_utilities"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.12"
color-eyre = "0.6"
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }