[package]
name = "todo_list"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6"
rusqlite = { version = "0.34.0", features = ["bundled"] }
ratatui = "0.29.0"

crossterm = "0.28.1"
uuid = { version = "1.2", features = ["v4"] }